import { Produto } from './produto.model';

export const PRODUTOS_MOCK: Produto[] = [
  {
    id: '1',
    nome: 'Camiseta REDE Clássica',
    categoria: 'camisetas',
    preco: 79.9,
    descricao: 'Camiseta 100% algodão com a marca REDE estampada no peito.',
    fotos: ['https://picsum.photos/seed/camiseta-classica-rede/480/480'],
    tamanhos: ['P', 'M', 'G', 'GG'],
    cores: ['Preto', 'Amarelo'],
    destaque: true,
    variacoes: [
      { tamanho: 'P', cor: 'Preto', estoque: 12 },
      { tamanho: 'P', cor: 'Amarelo', estoque: 8 },
      { tamanho: 'M', cor: 'Preto', estoque: 15 },
      { tamanho: 'M', cor: 'Amarelo', estoque: 10 },
      { tamanho: 'G', cor: 'Preto', estoque: 9 },
      { tamanho: 'G', cor: 'Amarelo', estoque: 6 },
      { tamanho: 'GG', cor: 'Preto', estoque: 4 },
      { tamanho: 'GG', cor: 'Amarelo', estoque: 0 },
    ],
  },
  {
    id: '2',
    nome: 'Camiseta REDE Minimalista',
    categoria: 'camisetas',
    preco: 74.9,
    descricao: 'Estampa discreta, para o dia a dia.',
    fotos: ['https://picsum.photos/seed/camiseta-minimalista-rede/480/480'],
    tamanhos: ['P', 'M', 'G', 'GG'],
    cores: ['Preto', 'Amarelo'],
    destaque: false,
    variacoes: [
      { tamanho: 'P', cor: 'Preto', estoque: 10 },
      { tamanho: 'P', cor: 'Amarelo', estoque: 10 },
      { tamanho: 'M', cor: 'Preto', estoque: 10 },
      { tamanho: 'M', cor: 'Amarelo', estoque: 10 },
      { tamanho: 'G', cor: 'Preto', estoque: 10 },
      { tamanho: 'G', cor: 'Amarelo', estoque: 10 },
      { tamanho: 'GG', cor: 'Preto', estoque: 10 },
      { tamanho: 'GG', cor: 'Amarelo', estoque: 10 },
    ],
  },
  {
    id: '3',
    nome: 'Camiseta REDE Edição Retiro',
    categoria: 'camisetas',
    preco: 84.9,
    descricao: 'Estampa exclusiva do último retiro da REDE.',
    fotos: ['https://picsum.photos/seed/camiseta-retiro-rede/480/480'],
    tamanhos: ['P', 'M', 'G'],
    cores: ['Preto'],
    destaque: false,
    variacoes: [
      { tamanho: 'P', cor: 'Preto', estoque: 5 },
      { tamanho: 'M', cor: 'Preto', estoque: 7 },
      { tamanho: 'G', cor: 'Preto', estoque: 3 },
    ],
  },
  {
    id: '4',
    nome: 'Moletom REDE Essencial',
    categoria: 'moletons',
    preco: 139.9,
    descricao: 'Moletom canguru, forro macio.',
    fotos: ['https://picsum.photos/seed/moletom-essencial-rede/480/480'],
    tamanhos: ['P', 'M', 'G', 'GG'],
    cores: ['Preto', 'Amarelo'],
    destaque: true,
    variacoes: [
      { tamanho: 'P', cor: 'Preto', estoque: 5 },
      { tamanho: 'P', cor: 'Amarelo', estoque: 5 },
      { tamanho: 'M', cor: 'Preto', estoque: 5 },
      { tamanho: 'M', cor: 'Amarelo', estoque: 5 },
      { tamanho: 'G', cor: 'Preto', estoque: 5 },
      { tamanho: 'G', cor: 'Amarelo', estoque: 5 },
      { tamanho: 'GG', cor: 'Preto', estoque: 5 },
      { tamanho: 'GG', cor: 'Amarelo', estoque: 5 },
    ],
  },
  {
    id: '5',
    nome: 'Moletom REDE Oversized',
    categoria: 'moletons',
    preco: 149.9,
    descricao: 'Corte oversized, streetwear.',
    fotos: ['https://picsum.photos/seed/moletom-oversized-rede/480/480'],
    tamanhos: ['M', 'G', 'GG'],
    cores: ['Preto'],
    destaque: false,
    variacoes: [
      { tamanho: 'M', cor: 'Preto', estoque: 6 },
      { tamanho: 'G', cor: 'Preto', estoque: 8 },
      { tamanho: 'GG', cor: 'Preto', estoque: 2 },
    ],
  },
  {
    id: '6',
    nome: 'Boné REDE',
    categoria: 'acessorios',
    preco: 59.9,
    descricao: 'Boné aba curva bordado.',
    fotos: ['https://picsum.photos/seed/bone-rede/480/480'],
    tamanhos: ['Único'],
    cores: ['Preto', 'Amarelo'],
    destaque: true,
    variacoes: [
      { tamanho: 'Único', cor: 'Preto', estoque: 20 },
      { tamanho: 'Único', cor: 'Amarelo', estoque: 15 },
    ],
  },
  {
    id: '7',
    nome: 'Squeeze REDE',
    categoria: 'acessorios',
    preco: 39.9,
    descricao: 'Squeeze 600ml com o logo da REDE.',
    fotos: ['https://picsum.photos/seed/squeeze-rede/480/480'],
    tamanhos: ['Único'],
    cores: ['Preto'],
    destaque: false,
    variacoes: [{ tamanho: 'Único', cor: 'Preto', estoque: 30 }],
  },
];
