import { Evento } from './evento.model';

export const EVENTOS_MOCK: Evento[] = [
  {
    id: '1',
    titulo: 'Retiro de Verão REDE',
    descricao: 'Um fim de semana de imersão, comunhão e descanso para os jovens da REDE.',
    dataHora: '2026-01-16T08:00:00.000Z',
    local: 'Sítio Vida Nova, Ibiúna',
    preco: 250,
    vagasTotais: 4,
    foto: 'https://picsum.photos/seed/retiro-verao-rede/480/480',
  },
  {
    id: '2',
    titulo: 'Encontro de Jovens',
    descricao: 'Noite de louvor, palavra e comunhão na igreja.',
    dataHora: '2026-02-06T22:00:00.000Z',
    local: 'Templo sede, Vila Maria',
    preco: 0,
    vagasTotais: 100,
    foto: 'https://picsum.photos/seed/encontro-jovens-rede/480/480',
  },
  {
    id: '3',
    titulo: 'Culto Especial de Missões',
    descricao: 'Culto dedicado ao envio e apoio aos missionários da igreja.',
    dataHora: '2026-02-20T19:00:00.000Z',
    local: 'Templo sede, Vila Maria',
    preco: 0,
    vagasTotais: 200,
    foto: 'https://picsum.photos/seed/culto-missoes-rede/480/480',
  },
  {
    id: '4',
    titulo: 'Acampamento de Carnaval',
    descricao: 'Três dias de atividades ao ar livre, esportes e devocionais.',
    dataHora: '2026-02-13T08:00:00.000Z',
    local: 'Chácara Monte Sião, Mairiporã',
    preco: 180,
    vagasTotais: 3,
    foto: 'https://picsum.photos/seed/acampamento-carnaval-rede/480/480',
  },
  {
    id: '5',
    titulo: 'Workshop de Louvor',
    descricao: 'Oficina prática de instrumentos e ministério de louvor para iniciantes.',
    dataHora: '2026-03-07T14:00:00.000Z',
    local: 'Templo sede, Vila Maria',
    preco: 40,
    vagasTotais: 20,
    foto: 'https://picsum.photos/seed/workshop-louvor-rede/480/480',
  },
  {
    id: '6',
    titulo: 'Vigília de Oração',
    descricao: 'Noite inteira de oração e adoração para encerrar o trimestre.',
    dataHora: '2026-03-28T22:00:00.000Z',
    local: 'Templo sede, Vila Maria',
    preco: 0,
    vagasTotais: 150,
    foto: 'https://picsum.photos/seed/vigilia-oracao-rede/480/480',
  },
];
